application: persistent-cal
version: 0-3
runtime: python
api_version: 1 # only existing version

handlers:
# precedence should be noted for any wildcards
- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon\.ico

- url: /.*
  script: main.py
