application: persistent-cal
version: 0-13
runtime: python27
api_version: 1  # only existing version
threadsafe: true  # for python27

handlers:
# precedence should be noted for any wildcards
- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon\.ico

- url: /stylesheets
  static_dir: stylesheets

- url: /javascript
  static_dir: javascript

- url: /scripts
  static_dir: scripts
  mime_type: "text/plain"

- url: /admin/interactive|/admin/interactive/execute
  script: interactive.APPLICATION
  login: admin

- url: /cron
  script: cron.APPLICATION
  login: admin

- url: /cron-weekly
  script: cron.APPLICATION
  login: admin

- url: /cron-monthly
  script: cron.APPLICATION
  login: admin

- url: /workers
  script: main.APPLICATION
  login: admin

- url: /.*
  script: main.APPLICATION

admin_console:
  pages:
  - name: Interactive Console
    url: /admin/interactive

builtins:
# for remote datastore calls
- remote_api: on
# for deferring cron requests to task queue
- deferred: on

libraries:
- name: jinja2
  version: "2.6"
