application: persistent-cal
version: 0-4
runtime: python
api_version: 1 # only existing version

handlers:
# precedence should be noted for any wildcards
- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon\.ico

- url: /stylesheets
  static_dir: stylesheets

- url: /javascripts
  static_dir: javascripts

- url: /cron
  script: cron.py
  login: admin

- url: /.*
  script: main.py

builtins:
# for remote datastore calls
- remote_api: on
# for deferring cron requests to task queue
- deferred: on
